export CATALINA_OPTS="$CATALINA_OPTS -DACQUISITION_JDBC_URL=${ACQUISITION_JDBC_URL} -DACQUISITION_DB_USER=${ACQUISITION_DB_USER} -DACQUISITION_DB_PASS=${ACQUISITION_DB_PASS} -DACQUISITION_DB_CLASS=${ACQUISITION_DB_CLASS}"
export CATALINA_OPTS="$CATALINA_OPTS -DEARS_JDBC_URL=${EARS_JDBC_URL} -DEARS_DB_USER=${EARS_DB_USER} -DEARS_DB_PASS=${EARS_DB_PASS} -DEARS_DB_CLASS=${EARS_DB_CLASS}"
