## ===================================================================
## Spring Boot configuration.
##
## ===================================================================

## ===================================================================
## TECHSAS-NG specific properties
## ===================================================================
##Profile to activate eurofleets jpa repository
##spring:
##  profiles:
##    active: "eurofleets"

## ===================================================================
## Standard Spring Boot properties.
## Full reference is available at:
## http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
## ===================================================================
##Profil to activate the old frontend
## To launch acquisition: profiles.active: acquisition, h2postgres
## To launch database: profiles.active: database, h2postgres
##                     to launch on same IP than "acquisition":
##                       -> change port / think about "databaseIP" in parameter.json
##                       -> change jdbc-url of embedded H2 db (application-h2postgres)
spring:
  profiles:
    active: acquisition, h2postgres
  main:
#    web-environment: true    # /!\ deprecated (replace by web-application-type - default=none)
    banner-mode : "off"       # Mode used to display the banner when the application runs. (default=console)
  mvc:
    favicon:
      enabled: false          # Whether to enable resolution of favicon.ico. (default=true)
  h2:
    console:
      enabled: true           # Whether to enable the console. (default=false)
management:
  health:
    ldap:
      enabled: false          # Whether to enable LDAP health check. (default=true)
#  security:
#    enabled: false            # /!\ this property has been removed
  endpoints:
    shutdown:
      enabled: true           # Whether to enable the shutdown endpoint.
#    beans:
#      sensitive: false        # /!\ sensitive flag has been removed
    health:
      show-details: ALWAYS    # When to show full health details. (default=never)
#      sensitive: false        # /!\ sensitive flag has been removed
    web:
      exposure:
        include: info,health,shutdown     # Endpoint IDs that should be included or '*' for all.
server:
  error:
    whitelabel:
      enabled: false          # Whether to enable the default error page displayed in browsers in case of a server error.
## change port (to 8282) to launch "database" profile on same IP than "acquisition"
#  port: 8282                  # Server HTTP port. (default = 8080)
#  session:
#    timeout: 1800            # /!\ deprecated. use server.servlet.session.timeout (default=30m)

## ===================================================================
## TECHSAS-NG specific properties
## ===================================================================
## Enabled web components
acquisition:
#  description:
#    url: "http://localhost:8080/api/descriptions/"
#  channel:
#    url: "http://localhost:8080/api/channels/"
#  device:
#    url: "http://localhost:8080/api/devices/"
#  broker:
#    topics:
#      configuration: "configuration.json"
#      devices: "devices.json"
#      status: "status.json"
#      log: "log.json"
#      heartbeat: "heartbeat"
#      rawSuffix: ".raw"
#      jsonSuffix: ".json"

  ## .. configuration service
#  configuration:
#    interval: 20000
  ## .. ntp status
#  status:
#    interval: 2000
  ntp:
#    interval: 30000
    host: ${NTP_HOST}
#    offset: 1000
#    delay: 1000
  sdiv:
    parameter:
      file: "classpath:config-dev/parameter.json"

  ## .. data visualization API
#  extraction:
#    maxNumValues: 100000
#    # .. .. milliseconds to consider data around a date in reference timestamping strategy
#    timestamping:
#      reference:
#        range: 500
#      predefined:
#        range: 500           # /!\ never used
#    # .. .. interval between which criterias must be cleared
#    criteria:
#      clearinterval: 1000    # /!\ never used
#      # .. .. criterias with more than ttl are removed (default 30 minutes)
#      ttl: 1800000           # /!\ never used

  ## .. drivers
#  device:
#    heartbeat:
#      interval: 10000
#    tcp:
#      autoreconnect:
#        interval: 1000

  ## meta common format device
#  metacommonformatdriver:
#    enabled: false
#    deviceIds:               # /!\ never used


##authentication
authentication:
#  jaas:
#    enabled: true
#    configuration: classpath:login.conf
#    name: Brest
#  ldap:
#    enabled: false
#    url: "ldap://ldap.ifremer.fr:389/dc=ifremer,dc=fr"
#    ou: "annuaire"
  ##authentication user list (@ConfigurationProperties)
  users:
    -   login: "admin"
        password: "secret"
        name: "Admin"
        roles :
          - "ROLE_ADMIN"
          - "ROLE_USER"
    -   login: "techsas"
        password: "techsas"
        name: "Techsas"
        roles : "ROLE_ADMIN"
    -   login: "chief"
        password: "Thalassa2017"
        name: "Head of mission"
        roles : "ROLE_MASTER"
    -   login: "user"
        password: "password"
        name: "User"
        roles : "ROLE_USER"
    -   login: "user1"
        password: "password"
        name: "User1"
        roles : "ROLE_USER"
    -   login: "sdivPcScience"
        password: "sdiv"
        name: "Sdiv PC Science"
        roles : "ROLE_SDIV"

## eurofleets db
#eurofleets:
#  db:
#    datasource:
#      url: "jdbc:mysql://localhost:3306/casino"
#      username: "ifremer"
#      password: "ifremer"
#      driverClassName: "com.mysql.jdbc.Driver"
#qgis:
#  projects:
#    directory: "./qgis"
#casino:
#    db:
#        datasource:
#            url:
#                jdbc_prefix: "jdbc:mysql://"
#                database: "/casino"
#                params: "?useUnicode=true"        # because database is Latin1 encoded
#            driverClassName: "com.mysql.jdbc.Driver"
###           driverClassName: "com.mysql.cj.jdbc.Driver" start with mysql-connector-java version: 8.0
###           Casino MySQL version: 5.1 => max mysql-connector-java version: 5.1.47 to prevent encoding problem
#    acquisition:   #Casino+ configuration (application-defs.props.xml)
#        server:
#            #            host: "134.246.151.251"  # VMNSECASINO
#            host: "localhost"
#            port: 6789
#            timeout: 20000
#        period: 15000
#        geoloc:
#            georef: "NOTGEOREFOK"
#            default: "999"

#settings:
#  database_max_size: 549755532413 # in bytes 128GiB
#  zda_port: 3015
#  url: "http://localhost:8080"

##Menu via intranet_pp
#menu:
#  enable: false
#  polling:
#    interval: 60000

#logging:
#    level:
#        org:
#            hibernate:
#                SQL: "DEBUG"
#                type:
#                    descriptor:
#                        sql:
#                            BasicBinder: "TRACE"
