## ===================================================================
## h2postgres profile
## ===================================================================

spring:
  profiles: h2postgres

  db:
#    jpa:
#      generate-ddl: "true"
#      show-sql: "false"
#      hibernate:
#        ddl-auto: "update"
    datasource:   # (@ConfigurationProperties)
#      jdbc-url: "jdbc:h2:mem:extraction" # for "database" profile
      jdbc-url: "jdbc:h2:file:./cruises/test/archive;MV_STORE=FALSE;DB_CLOSE_ON_EXIT=FALSE" # for "acquisition" profile
      driver-class-name: "org.h2.Driver"
      username: "sa"
      password: "sa"

## H2 database options:
##      MVCC: Multi-Version Concurrency Control
##      MV_STORE: For H2 version 1.4 and newer, the MVStore is the default storage engine (store in .mv.db-files)
##      DB_CLOSE_ON_EXIT=FALSE: Don't Close a Database when the VM Exits => prevent "SQL Error: 90121, SQLState: 90121 ERROR - Database is already closed"

#  extdb:
#    interval_max:
#      calendar: 2    # Calendar.MONTH (= 2)
#      nb: 2
#    jpa:
#      generate-ddl: "true"
#      show-sql: "false"
#      hibernate:
#        ddl-auto: "none"
#    datasource:
#      jdbc-url: "jdbc:postgresql://localhost:5432/cruises"
#      driver-class-name: "org.postgresql.Driver"
#      username: "postgres"
#      password: "postgres"